language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t lkulik/deeplearning-cpu -f deeplearning/Dockerfile .
  - docker build -t lkulik/deeplearning-gpu -f deeplearning/Dockerfile.gpu .
  - docker run -d -p 8888:8888 -ti lkulik/deeplearning-cpu
  - docker run -d -p 9999:9999 -ti lkulik/deeplearning-gpu

script:
  - docker ps | grep -q deeplearning-cpu
  - docker ps | grep -q deeplearning-gpu
